modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Axieum/Chatter/issues"
displayURL="https://github.com/Axieum/Chatter"
logoFile="logo.png"
authors="Axieum"

[[mods]]
modId="chatter"
version="${file.jarVersion}"
displayName="Chatter"
description='''
Slightly change the format of the in-game chat
'''

[[dependencies.chatter]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chatter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
